[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style= "Regular" }
size = 15.0
glyph_offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

[selection]
save_to_clipboard = true

[window]
dimensions = { columns = 140, lines = 35 }
padding = { x = 4, y = 4 }
decorations = "Full"
dynamic_title = true

[terminal]
shell = { program = "/bin/zsh" }
